services:

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus_alert_rules.yml:/etc/prometheus/rules.yml
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.external-url=https://example-prometheus.com

  alertmanager:
    image: "prom/alertmanager"
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./data/alertmanager:/alertmanager
      - ./scripts/alertmanager_wrapper.sh:/alertmanager_wrapper.sh
    env_file:
      - .env
    entrypoint: /alertmanager_wrapper.sh

  pushgateway:
    image: "prom/pushgateway"
    ports:
      - "9091:9091"
    volumes:
      - ./data/pushgateway:/data
    entrypoint: /bin/pushgateway
    command: >
      --persistence.file="/data/metric.store"
      --persistence.interval=10s

  grafana:
    image: "grafana/grafana"
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"

  ubuntu:
    build: .
    ports:
      - "9100:9100"
      - "8000:8000"
    command: >
      ./node_exporter
