tls_server_config:
  cert_file: /node_exporter-1.7.0.linux-amd64/node_exporter.crt
  key_file: /node_exporter-1.7.0.linux-amd64/node_exporter.key

# create with htpasswd
# htpasswd -nBC 10 "" | tr -d ':\n'; echo
basic_auth_users:
  user: $2y$10$Y9E7.0XVuVQtqZd184uF5OIsrdWFZDJT4uihGyCF.sjvMpjD42cNe