global:
  resolve_timeout: 1m
  slack_api_url: ${SLACK_API_URL}

route:
  receiver: 'slack-notifications'
  repeat_interval: 3h

  routes:
  - matchers:
    - severity=page
    receiver: slack-notifications

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alertmanager'
    send_resolved: true