groups:
- name: Number checking
  rules:
  - alert: my_number too high
    expr: my_number > 5
    for: 15s
    labels:
      severity: page
    annotations:
      summary: We like to keep this number low